# Generated by Django 5.0.6 on 2024-06-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imager', '0004_image_delete_imagedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
