# Generated by Django 5.0.6 on 2024-06-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imager', '0008_plan_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ForeignKey(default='Default.svg', on_delete=django.db.models.deletion.CASCADE, to='Imager.image', verbose_name='Photo'),
        ),
    ]
