# Generated by Django 5.0.6 on 2024-06-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imager', '0009_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imager.image', verbose_name='Photo'),
        ),
    ]
