# Generated by Django 5.0.6 on 2024-06-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imager', '0010_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Imager.image', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Imager.plan', verbose_name='Plan'),
        ),
    ]
