# Generated by Django 5.0.6 on 2024-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imager', '0014_alter_image_image_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='image',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
