# Generated by Django 5.0.6 on 2024-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imager', '0015_image_description_image_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
