# Generated by Django 5.0.6 on 2024-08-07 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imager', '0020_alter_profile_user_viewedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_private',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Private'),
        ),
        migrations.AlterField(
            model_name='image',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image Limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='space_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Space Limit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Imager.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='viewedimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Imager.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='viewedimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
